Busskort/Controllers/AnmalanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Busskort.Models;

namespace Busskort.Controllers
{
    public class AnmalanController : Controller
    {
        // GET: Anmalan
        public ActionResult Index()
        {
            // Create a dropdown with ViewBag from a class
            DropdownList dropdown = new DropdownList();
            ViewBag.DropDownYears = dropdown.GetYearDropDown();

            return View();
        }

        [HttpPost]
        [ValidateInput(true)] // Prevent XSS
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // Use class from reference, otherwise errors will occur when passing the object to the service
                BusskortServiceReference.Anmälan newAnmälan = new BusskortServiceReference.Anmälan();

                // Skola och årskurs
                newAnmälan.Årskurs = Convert.ToInt32(collection["year"]);
                newAnmälan.Skola = Convert.ToString(collection["skolaNamn"]);

                // Barn
                newAnmälan.barnPersonnummer = Convert.ToInt32(collection["barnPersonnummer"]);
                newAnmälan.barnFörnamn = Convert.ToString(collection["barnFörnamn"]);
                newAnmälan.barnEfternamn = Convert.ToString(collection["barnEfternamn"]);

                // Målsman
                newAnmälan.FörälderPersonnummer = Convert.ToInt32(collection["FörälderPersonnummer"]);
                newAnmälan.Förnamn = Convert.ToString(collection["Förnamn"]);
                newAnmälan.Efternamn = Convert.ToString(collection["Efternamn"]);

                //Kontakt 
                newAnmälan.E_post = Convert.ToString(collection["E_post"]);
                newAnmälan.Telefon = Convert.ToInt32(collection["inputTelefon"]);

                // Adress
                newAnmälan.Adress = Convert.ToString(collection["Adress"]);
                newAnmälan.Postnummer = Convert.ToInt32(collection["Postnummer"]);
                newAnmälan.Ort = Convert.ToString(collection["Ort"]);

                BusskortServiceReference.Service1Client client = new BusskortServiceReference.Service1Client();
                EmailHandler email = new EmailHandler();

                // Insert into database
                client.CreateAnmälan(newAnmälan);
                email.CreateRegistrationEmail("Ansökan om busskort", newAnmälan);
            }
            catch
            {

            }

            return RedirectToAction("Index");
        }
    }
}

Busskort/Views/Shared/_AdminAnmalanPart.cshtml
@model Busskort.BusskortServiceReference.Anmälan

<div class="form-row">

    @Html.HiddenFor(m => m.ID)

    <div class="form-group col-md-6">
        <h3 class="formlabel" style="font-family: sans-serif">Skola</h3><br />

        <label for="exampleFormControlSelect1"><b>Årskurs</b></label>
        @Html.DropDownList("year", (IEnumerable<SelectListItem>)ViewBag.DropDownYears, new { id = "exampleFormControlSelect1", @class = "form-control", @disabled = "disabled" })

        <label for="inputSkola"><b>Skola</b></label>
        <input type="text" class="form-control" value="@Model.Skola" id="inputSkola" name="skolaNamn" readonly>
    </div>

    <div class="form-group col-md-6">
        <h3 class="formlabel" style="font-family: sans-serif">Barn</h3><br />
        <label for="inputB_Personnummer"><b>Personnummer</b></label>
        <input type="text" class="form-control" value="@Model.barnPersonnummer" id="inputB_Personnummer" placeholder="ÅÅMMDD-XXXX" name="barnPersonnummer" readonly>
        <label for="inputB_fornamn"><b>Förnamn</b></label>
        <input type="text" class="form-control" value="@Model.barnFörnamn" id="inputB_fornamn" placeholder="Förnamn" name="barnFörnamn" readonly>
        <label for="inputB_efternamn"><b>Efternamn</b></label>
        <input type="text" class="form-control" value="@Model.barnEfternamn" id="inputB_efternamn" placeholder="Efternamn" name="barnEfternamn" readonly>
    </div>

    <div class="form-group col-md-6">
        <h3 class="formlabel" style="font-family: sans-serif">Målsman</h3><br />
        <label for="inputM_Personnummer"><b>Personnummer</b></label>
        <input type="text" class="form-control" value="@Model.FörälderPersonnummer" id="inputF_Personnummer" placeholder="ÅÅMMDD-XXXX" name="FörälderPersonnummer" readonly>
        <label for="inputM_fornamn"><b>Förnamn</b></label>
        <input type="text" class="form-control" value="@Model.Förnamn" id="inputM_fornamn" placeholder="Förnamn" name="Förnamn" readonly>
        <label for="inputM_efternamn"><b>Efternamn</b></label>
        <input type="text" class="form-control" value="@Model.Efternamn" id="inputM_efternamn" placeholder="Efternamn" name="Efternamn" readonly>
    </div>

    <div class="form-group col-md-6">
        <h3 class="formlabel" style="font-family: sans-serif">Kontakt</h3><br />

        <label for="inputEmail"><b>E-post</b></label>
        <input type="email" class="form-control" value="@Model.E_post" id="inputEmail" placeholder="E-post" name="E_post" readonly>
        <label for="inputTelefon"><b>Telefon</b></label>
        <input type="text" class="form-control" value="@Model.Telefon" id="inputTelefon" placeholder="Telefonnummer" name="inputTelefon" readonly>
    </div>

    <div class="form-group col-md-6">
        <h3 class="formlabel" style="font-family: sans-serif">Adress</h3><br />

        <label for="inputAdress"><b>Adress</b></label>
        <input type="text" class="form-control" value="@Model.Adress" id="inputAdress" placeholder="Gatunamn t.ex. Mjölnaregatan 16" name="Adress" readonly>
        <label for="inputPostnummer"><b>Postnummer</b></label>
        <input type="text" class="form-control" value="@Model.Postnummer" id="inputPostnummer" placeholder="Postnummer" name="Postnummer" readonly>
        <label for="inputOrt"><b>Ort</b></label>
        <input type="text" class="form-control" value="@Model.Ort" id="inputOrt" placeholder="Ort" name="Ort" readonly>

    </div>
</div>

Busskort/Views/Shared/_MasterPageNormal.cshtml
<!DOCTYPE html>

<html>
<head>
    <script src="~/Scripts/popper.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Custom/Anmälan/Index.css" rel="stylesheet" />
    <link href="~/Custom/MasterPage/MasterPage.css" rel="stylesheet" />
    <meta name="viewport" content="width=device-width" />
    <title>Ansökan om busskort</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <a class="navbar-brand" href="#">Busskort</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    @Html.ActionLink("Ansök", "Index", "Anmalan", null, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Admin", "Index", "Admin", null, new { @class = "nav-link" })
                </li>
            </ul>
        </div>
    </nav>

    <div>
        @RenderBody()
    </div>
@*<footer class="footer">
    <div>
        <p>Datum: <span id="datetime"></span></p>
    </div>
</footer>*@
<script>
    var dt = new Date();
    document.getElementById("datetime").innerHTML = dt.toLocaleDateString();
</script>
</body>
</html>